import { StyleSheet } from "react-native";
import { SCREEN_HEIGHT, SCREEN_WIDTH } from "../constants/ReelsConstants";

// ═══════════════════════════════════════════════════════════════════════
//  STYLES
// ═══════════════════════════════════════════════════════════════════════

export const styles = StyleSheet.create({
  list: { flex: 1, backgroundColor: "#000" },
  center: { flex: 1, backgroundColor: "#000", justifyContent: "center", alignItems: "center" },
  container: { width: SCREEN_WIDTH, height: SCREEN_HEIGHT, backgroundColor: "#000" },
  heartOverlay: { position: "absolute", top: "40%", left: "50%", marginLeft: -55, marginTop: -55 },
  muteBtn: {
    position: "absolute",
    top: 50,
    right: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  rightBar: { position: "absolute", right: 10, bottom: 110, alignItems: "center" },
  iconBtn: { alignItems: "center", marginBottom: 22 },
  iconLabel: { color: "#fff", fontSize: 12, marginTop: 4, fontWeight: "600" },
  avatar: { width: 46, height: 46, borderRadius: 23, borderWidth: 1.5, borderColor: "#dddada" },
  plusBtn: {
    position: "absolute",
    bottom: -8,
    alignSelf: "center",
    backgroundColor: "#ff2d55",
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  bottomInfo: { position: "absolute", left: 14, right: 80, bottom: 80 },
  username: { color: "#fff", fontWeight: "700", fontSize: 15, marginBottom: 6 },
  caption: { color: "#eee", fontSize: 13 },
  pauseOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  overlay: { flex: 1, justifyContent: "flex-end" },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.5)" },
  sheet: {
    backgroundColor: "#161616",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  handle: { width: 40, height: 4, backgroundColor: "#555", borderRadius: 2, alignSelf: "center", marginVertical: 8 },
  sheetTitle: { color: "#fff", fontWeight: "700", fontSize: 16, textAlign: "center", marginBottom: 10 },
  empty: { color: "#888", textAlign: "center", marginTop: 30 },
  commentRow: { flexDirection: "row", marginBottom: 16 },
  commentAvatar: { width: 34, height: 34, borderRadius: 17, marginRight: 10 },
  commentUser: { color: "#bbb", fontSize: 12, fontWeight: "600", marginBottom: 2 },
  commentText: { color: "#fff", fontSize: 14 },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#2a2a2a",
    paddingVertical: 10,
  },
  input: {
    flex: 1,
    color: "#fff",
    backgroundColor: "#242424",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 10,
    maxHeight: 100,
  },
  contact: { alignItems: "center", marginRight: 18, width: 70 },
  contactAvatar: { width: 56, height: 56, borderRadius: 28, marginBottom: 6 },
  contactName: { color: "#fff", fontSize: 12 },
  sentLabel: { color: "#0af", fontSize: 10, marginTop: 2 },
  actionsRow: { flexDirection: "row", justifyContent: "space-around", marginTop: 10, marginBottom: 6 },
  actionBtn: { alignItems: "center" },
  actionIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#2a2a2a",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
  },
  actionLabel: { color: "#ddd", fontSize: 11, textAlign: "center", maxWidth: 80 },
  cancelBtn: { marginTop: 10, paddingVertical: 12, alignItems: "center", borderTopWidth: 1, borderTopColor: "#2a2a2a" },
  cancelText: { color: "#fff", fontWeight: "600", fontSize: 15 },
  row: { flexDirection: "row", alignItems: "center", paddingVertical: 14 },
  rowLabel: { color: "#fff", fontSize: 15, marginLeft: 16 },
});